"""Digest generator – builds HTML email from unsent articles."""

import logging
from datetime import date
from typing import Dict, List
from collections import defaultdict
from sqlalchemy.orm import Session

from app.database import SessionLocal
from app.models import Article

logger = logging.getLogger(__name__)


def _build_html(grouped: Dict[str, List[Article]], today: str) -> str:
    """Generate the HTML email body."""
    html_parts = [
        '<!DOCTYPE html>',
        '<html><head><meta charset="utf-8"></head>',
        '<body style="font-family:Segoe UI,Arial,sans-serif;max-width:700px;margin:0 auto;padding:20px;background:#f9f9f9;">',
        f'<h1 style="color:#1a1a2e;border-bottom:3px solid #16213e;padding-bottom:10px;">Morning News Brief – {today}</h1>',
    ]

    # Custom topic ordering: named topics first, General last
    topic_order = sorted(grouped.keys(), key=lambda t: (t == "General", t))

    for topic_name in topic_order:
        articles = grouped[topic_name]
        html_parts.append(
            f'<h2 style="color:#16213e;margin-top:25px;border-left:4px solid #e94560;padding-left:10px;">{topic_name}</h2>'
        )
        html_parts.append('<ul style="list-style:none;padding:0;">')
        for art in articles:
            html_parts.append(
                f'<li style="margin:8px 0;padding:8px 12px;background:#fff;border-radius:4px;">'
                f'• <a href="{art.url}" style="color:#0f3460;text-decoration:none;font-weight:500;">{art.title}</a>'
                f'<br><span style="font-size:12px;color:#888;">{art.source}</span>'
                f'</li>'
            )
        html_parts.append('</ul>')

    html_parts.append(
        '<hr style="margin-top:30px;border:1px solid #ddd;">'
        '<p style="font-size:12px;color:#999;text-align:center;">This digest was automatically generated by the News Monitoring System.</p>'
        '</body></html>'
    )
    return "\n".join(html_parts)


def generate_digest() -> tuple:
    """
    Query unsent articles, group by topic, build HTML.
    Returns (html_string, article_ids_list) or (None, []) if no articles.
    """
    db: Session = SessionLocal()
    try:
        articles = (
            db.query(Article)
            .filter(Article.sent_status == False)
            .order_by(Article.topic, Article.date_scraped.desc())
            .all()
        )

        if not articles:
            logger.info("No unsent articles for digest.")
            return None, []

        grouped = defaultdict(list)
        for art in articles:
            grouped[art.topic or "General"].append(art)

        today_str = date.today().strftime("%B %d, %Y")
        html = _build_html(grouped, today_str)
        article_ids = [art.id for art in articles]

        logger.info(f"Digest generated with {len(articles)} articles across {len(grouped)} topics.")
        return html, article_ids
    finally:
        db.close()
